name: Maven Continaer
on:
  push:
    branches: [ master ]
jobs:
  maven-container-job:
    runs-on: ubuntu-latest
#     container:
#       image: maven:3.8.6-jdk-8
      #env:
      #  NODE_ENV: development
      #ports:
      #  - 80
      # volumes:
      #  - my_docker_volume:/volume_mount
      # options: --cpus 1
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn clean package
