name: Maven Continaer
on:
  push:
    branches: [ master ]
jobs:
  maven-container-job:
    runs-on: ubuntu-latest
#     container:
#       image: maven:3.8.6-jdk-8
      #env:
      #  NODE_ENV: development
      #ports:
      #  - 80
      # volumes:
      #  - my_docker_volume:/volume_mount
      # options: --cpus 1
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build with Maven
        run: mvn clean package
      - name: List files
        run: |
            pwd
            ls -la
            ls /
    
        
